services:
  - type: web
    name: anyang-visitlog
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
  - key: ADMIN_PASSWORD
    value: "1234"

